def select_set(self, state: bool) -> None: ...
def select_get(self) -> bool: ...
def hide_set(self, state: bool) -> None: ...
def hide_get(self) -> bool: ...
def hide_viewport_set(self, state: bool) -> None: ...
def hide_render_set(self, state: bool) -> None: ...
def temp_override(self, window=None, area=None, region=None, **kwargs) -> Any: ...