@classmethod
def draw_handler_add(cls, callback: Callable, args: tuple, region_type: str, draw_type: str) -> object: ...
@classmethod
def draw_handler_remove(cls, handler: object, region_type: str) -> None: ...